name: AppImage

on:
  push:
    branches: [ "master", "qt6", "qe3-test" ]
  pull_request:
    branches: [ "master", "qt6" ]

jobs:
  ubuntu-qt6:
    name: Qt 6.5 / Ubuntu 22.04
    runs-on: ubuntu-20.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup CMake
        uses: ./.github/actions/cmake
        with:
          additional_cmake_args: -DCMAKE_INSTALL_PREFIX='${{ github.workspace }}/install/usr'

      - name: Create AppImage
        uses: ./.github/actions/appimage
